version: '3'
services:
  accesspoint:
    build: ./manjaroAP
    network_mode: "host"
    privileged: true
    environment:
      - RESTRICTEDMODE=true
      - IWIRELESS=wlo1
      - IINTERNET=wlo1
      - ESSID=prueba
      - PASS=12345678
      - ALUMNSMACS=${MACS}
      - WHITEURLS=${WHITES}
      - FORCECHANNEL=true
      - CHANNEL=1
  monitor:
    build: ./monitorAP
    network_mode: "host"
    ports:
      - "9595:9595"
  notificaciones:
    build: ./notificacionesAP
    ports:
      - "8000:8000"
  examenes_practicos:
    build: ./examenesPracticos
    network_mode: "host"
    ports:
      - "8100:8100"
    volumes:
      - ./examenesPracticos/examenesPracticos:/code
    environment:
      - DIRECTORIO_RESPUESTA=examen1
      - TEMPLATE_EXAMEN=${TEMPLATE}
