# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('idalumno', models.AutoField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('usuario', models.CharField(blank=True, max_length=8, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=8, null=True)),
                ('logueado', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'Alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosEjercicios',
            fields=[
                ('idalumnos_ejercicios', models.AutoField(db_column='idAlumnos_Ejercicios', primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('horasubida', models.DateTimeField(db_column='horaSubida')),
                ('calificado', models.IntegerField(blank=True, null=True)),
                ('puntosobtenidos', models.DecimalField(db_column='puntosObtenidos', decimal_places=0, max_digits=10, verbose_name='puntos')),
            ],
            options={
                'db_table': 'Alumnos_Ejercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosGrupos',
            fields=[
                ('idalumnos_grupos', models.AutoField(db_column='idAlumnos_Grupos', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Alumnos_Grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('idejercicios', models.AutoField(db_column='idEjercicios', primary_key=True, serialize=False)),
                ('idincisoxml', models.CharField(db_column='idIncisoXML', max_length=45)),
                ('correcto', models.CharField(blank=True, max_length=45, null=True)),
                ('puntaje', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'Ejercicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('idexamen', models.AutoField(db_column='idExamen', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('periodo', models.CharField(blank=True, max_length=45, null=True)),
                ('carrera', models.CharField(blank=True, max_length=45, null=True)),
                ('universidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Examenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('idgrupos', models.AutoField(db_column='idGrupos', primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Grupos',
                'managed': False,
            },
        ),
    ]
